### ISSUE TITLE
Move to main from wiki

### ISSUE THREAD

**Issue by buchizo** [azure-ad-b2c/azureadb2ccommunity.io#1]
Hi team,

This repository is so awesome for custom policies developers! I love it. If possible I will be able to help this. 
However currently I difficult contribute because these docs is wiki pages.

My opinions as follows:
- Move to code repository (main) from wiki pages
- Publish documents to GitHub pages
- Add license

If you can do these, I will add some docs, for example I add localize version such as Japanese because recently AADB2C custom policy is so fashionable in Japan.

**Comment by yoelhor** [comment]
Thanks for your feedback. We are checking this approach. I'll keep you posted soon

**Comment by vi-nu** [comment]
@buchizo  thank you so much for your feedback. Now the wiki has moved to git pages: https://azure-ad-b2c.github.io/azureadb2ccommunity.io/ but the website is still in the process of making. I also add the license.
