### ISSUE TITLE
Under IEF Wiki images are 404

### ISSUE THREAD

**Issue by buchizo** [azure-ad-b2c/azureadb2ccommunity.io#3]
[IEF wiki's](https://azure-ad-b2c.github.io/azureadb2ccommunity.io/docs/custom-policy-concepts/) images are 404

![image](https://user-images.githubusercontent.com/1254213/79718897-2a477000-8318-11ea-85a8-b185312c01a1.png)

**Comment by yoelhor** [comment]
Please use the direct link https://github.com/azure-ad-b2c/azureadb2ccommunity.io/wiki

**Comment by JasSuri** [comment]
Fixed
