### ISSUE TITLE
Azure AD B2C Changlog is missing a reference

### ISSUE THREAD

**Issue by Norrch2** [azure-ad-b2c/azureadb2ccommunity.io#4]
Hello,

I was reviewing the Azure AD B2C Changelog and under the May 20th changes there is a bullet item: Azure AD B2C to Azure AD B2C federation is supported.

There is no reference to the documentation to find out more details. I also have searched the B2C documentation on docs.microsoft.com and am unable to find any reference to this. 

Please update the changelog with a link.

**Comment by JasSuri** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-b2c?pivots=b2c-custom-policy
